"""Persist metadata images

Revision ID: 341d84d28bd9
Revises: 1e13d09b8661
Create Date: 2023-10-02 20:42:18.552967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '341d84d28bd9'
down_revision: Union[str, None] = '1e13d09b8661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metadataimage', sa.Column('mime', sa.String(), nullable=True))
    op.add_column('metadataimage', sa.Column('source_image_url', sa.String(), nullable=True))
    op.alter_column('metadataimage', 'data',
               existing_type=sa.BLOB(),
               nullable=True)
    op.drop_constraint(None, 'metadataimage', type_='foreignkey')
    op.drop_column('metadataimage', 'page_metadata_id')
    op.add_column('pagemetadata', sa.Column('price', sa.String(), nullable=True))
    op.add_column('pagemetadata', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('pagemetadata', sa.Column('image_id', sa.Integer(), nullable=True))
    op.alter_column('pagemetadata', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pagemetadata', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pagemetadata', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pagemetadata', 'site_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'pagemetadata', 'metadataimage', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pagemetadata', type_='foreignkey')
    op.alter_column('pagemetadata', 'site_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pagemetadata', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pagemetadata', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pagemetadata', 'image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('pagemetadata', 'image_id')
    op.drop_column('pagemetadata', 'currency')
    op.drop_column('pagemetadata', 'price')
    op.add_column('metadataimage', sa.Column('page_metadata_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'metadataimage', 'pagemetadata', ['page_metadata_id'], ['id'])
    op.alter_column('metadataimage', 'data',
               existing_type=sa.BLOB(),
               nullable=False)
    op.drop_column('metadataimage', 'source_image_url')
    op.drop_column('metadataimage', 'mime')
    # ### end Alembic commands ###
