"""Add public itemize flag

Revision ID: 8d66dec5479b
Revises: f78a6f4d15f3
Create Date: 2023-10-08 08:33:52.682974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d66dec5479b'
down_revision: Union[str, None] = 'f78a6f4d15f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itemize', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itemize', schema=None) as batch_op:
        batch_op.drop_column('public')

    # ### end Alembic commands ###
