"""Persist metadata images

Revision ID: aae5cf920a5c
Revises: e6bf2dae3483
Create Date: 2023-10-02 21:36:33.599794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae5cf920a5c'
down_revision: Union[str, None] = 'e6bf2dae3483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metadataimage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mime', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source_image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metadataimage', schema=None) as batch_op:
        batch_op.drop_column('source_image_url')
        batch_op.drop_column('mime')

    # ### end Alembic commands ###
