"""Add page metadata overrides

Revision ID: f78a6f4d15f3
Revises: aae5cf920a5c
Create Date: 2023-10-05 20:06:36.436521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78a6f4d15f3'
down_revision: Union[str, None] = 'aae5cf920a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagemetadataoverride',
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('site_name', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['metadataimage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_metadata_override_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'pagemetadataoverride', ['page_metadata_override_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('page_metadata_override_id')

    op.drop_table('pagemetadataoverride')
    # ### end Alembic commands ###
