name: Backend Tests

on:
  push:

jobs:
  check-typing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade
        pip install -r backend/requirements.txt
        pip install mypy
        mypy --install-types --non-interactive
    - name: Run mypy
      run: |
        python -m mypy backend/itemize
  
  test-migrations:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade
        pip install -r backend/requirements.txt
    - name: Run migrations
      env:
        DB_URI: test.sqlite
      run: |
        cd backend
        alembic upgrade head
      